### ISSUE TITLE
Hello! I recently came across your model and found it very practical. Could you please advise on how to apply this model to my own dataset? Looking forward to your response.

### ISSUE THREAD

**Issue by Liavege** [EQTPartners/TSDE#1]
Also，i find some little problems in the "visualize_examples_imputation.ipynb",it need import os
import sys

**Comment by ZinebSenane** [comment]
Hi Liavege! 

Thanks for your interest in our work! To apply TSDE to your own dataset, you will need to create a dataloader file, experiment config and script. You can take a look at the src/data_loader folder, there are scripts of processing the different datasets we used in our experiments. Let me know if you have any questions regarding them. The config file is also straightforward there are comments about the different args. The experiment scripts can be found in src/experiments. What is your use case (experiment type), and provide me with more details about the dataset if you need more help!

Thanks for the minor errors in the imports I will fix them!
